### ISSUE TITLE
Switch build system

### ISSUE THREAD

**Issue by cmnrd** [chrism333/yalla#4]
Decide for a future build system and adopt existing configurations. Possibly scons is a good choice: http://jaanus.tech-thing.org/everything-thats-not-hardware/using-scons-compile-program-avr-atmega/

**Comment by stfngrt** [comment]
This might also be of some help understanding how scons might be used. https://github.com/metala/avr-gcc-scons-skel

**Comment by cmnrd** [comment]
We definitely need to switch away from premake! I had issues because premake adds various default compiler flags, which in my case lead to garbage output. (Probably because of faulty linker script)
